version: '3.7'
services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MAIL_PASS=${MAIL_PASS}"
    ports:
      - 27018:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "TOKEN=${TOKEN}"
    depends_on:
      - mongo_db
  